require "spree_core"
require "spree_mailchimp/engine"
require "spree_mailchimp/version"
require "spree_mailchimp/base"
require "spree_mailchimp/customer"
require "spree_mailchimp/list"
require "spree_mailchimp/order"
require "spree_mailchimp/product"
